// Kept free of imports on purpose. The enum is needed by the map data, the
// slices and state-types, all of which are dependencies of the useItemData
// hook - so re-exporting it from there would make those modules import a hook
// that imports them back, and whichever module entered the cycle first would
// see ItemType as undefined.
export enum ItemType {
  MasterBall = "master-ball", // DONE
  UltraBall = "ultra-ball", // DONE
  GreatBall = "great-ball", // DONE
  PokeBall = "poke-ball", // DONE
  TownMap = "town-map",
  Bicycle = "bicycle",
  SafariBall = "safari-ball",
  Pokedex = "pokedex",
  MoonStone = "moon-stone", // DONE
  Antidote = "antidote",
  BurnHeal = "burn-heal",
  IceHeal = "ice-heal",
  Awakening = "awakening",
  ParlyzHeal = "parlyz-heal",
  FullRestore = "full-restore",
  MaxPotion = "max-potion", // DONE
  HyperPotion = "hyper-potion", // DONE
  SuperPotion = "super-potion", // DONE
  Potion = "potion", // DONE
  BoulderBadge = "boulder-badge", // DONE
  CascadeBadge = "cascade-badge", // DONE
  ThunderBadge = "thunder-badge", // DONE
  RainbowBadge = "rainbow-badge", // DONE
  SoulBadge = "soul-badge", // DONE
  MarshBadge = "marsh-badge", // DONE
  VolcanoBadge = "volcano-badge", // DONE
  EarthBadge = "earth-badge", // DONE
  EscapeRope = "escape-rope",
  Repel = "repel",
  OldAmber = "old-amber",
  FireStone = "fire-stone", // DONE
  ThunderStone = "thunder-stone", // DONE
  WaterStone = "water-stone", // DONE
  HpUp = "hp-up",
  Protein = "protein",
  Iron = "iron",
  Carbos = "carbos",
  Calcium = "calcium",
  RareCandy = "rare-candy",
  DomeFossil = "dome-fossil",
  HelixFossil = "helix-fossil",
  SecretKey = "secret-key",
  BikeVoucher = "bike-voucher",
  XAccuracy = "x-accuracy",
  LeafStone = "leaf-stone", // DONE
  CardKey = "card-key",
  Nugget = "nugget", // DONE
  PpUp = "pp-up", // DONE
  PokeDoll = "poke-doll",
  FullHeal = "full-heal",
  Revive = "revive", // DONE
  MaxRevive = "max-revive", // DONE
  GuardSpec = "guard-spec",
  SuperRepel = "super-repel",
  MaxRepel = "max-repel",
  DireHit = "dire-hit",
  Coin = "coin",
  FreshWater = "fresh-water", // DONE
  SodaPop = "soda-pop", // DONE
  Lemondade = "lemonade", // DONE
  SSTicket = "ss-ticket",
  GoldTeeth = "gold-teeth",
  XAttack = "x-attack",
  XDefend = "x-defend",
  XSpeed = "x-speed",
  XSpecial = "x-special",
  CoinCase = "coin-case",
  OaksParcel = "oaks-parcel",
  ItemFinder = "item-finder",
  SilphScope = "silph-scope",
  PokeFlute = "poke-flute",
  LiftKey = "lift-key",
  ExpAll = "exp-all",
  OldRod = "old-rod",
  GoodRod = "good-rod",
  SuperRod = "super-rod",
  Ether = "ether", // DONE
  MaxEther = "max-ether", // DONE
  Elixer = "elixer", // DONE
  MaxElixer = "max-elixer", // DONE
  Hm01 = "hm01", // DONE
  Hm02 = "hm02", // DONE
  Hm03 = "hm03", // DONE
  Hm04 = "hm04", // DONE
  Hm05 = "hm05", // DONE
  Tm01 = "tm01", // DONE
  Tm02 = "tm02", // DONE
  Tm03 = "tm03", // DONE
  Tm04 = "tm04", // DONE
  Tm05 = "tm05", // DONE
  Tm06 = "tm06", // DONE
  Tm07 = "tm07", // DONE
  Tm08 = "tm08", // DONE
  Tm09 = "tm09", // DONE
  Tm10 = "tm10", // DONE
  Tm11 = "tm11", // DONE
  Tm12 = "tm12", // DONE
  Tm13 = "tm13", // DONE
  Tm14 = "tm14", // DONE
  Tm15 = "tm15", // DONE
  Tm16 = "tm16", // DONE
  Tm17 = "tm17", // DONE
  Tm18 = "tm18", // DONE
  Tm19 = "tm19", // DONE
  Tm20 = "tm20", // DONE
  Tm21 = "tm21", // DONE
  Tm22 = "tm22", // DONE
  Tm23 = "tm23", // DONE
  Tm24 = "tm24", // DONE
  Tm25 = "tm25", // DONE
  Tm26 = "tm26", // DONE
  Tm27 = "tm27", // DONE
  Tm28 = "tm28", // DONE
  Tm29 = "tm29", // DONE
  Tm30 = "tm30", // DONE
  Tm31 = "tm31", // DONE
  Tm32 = "tm32", // DONE
  Tm33 = "tm33", // DONE
  Tm34 = "tm34", // DONE
  Tm35 = "tm35", // DONE
  Tm36 = "tm36", // DONE
  Tm37 = "tm37", // DONE
  Tm38 = "tm38", // DONE
  Tm39 = "tm39", // DONE
  Tm40 = "tm40", // DONE
  Tm41 = "tm41", // DONE
  Tm42 = "tm42", // DONE
  Tm43 = "tm43", // DONE
  Tm44 = "tm44", // DONE
  Tm45 = "tm45", // DONE
  Tm46 = "tm46", // DONE
  Tm47 = "tm47", // DONE
  Tm48 = "tm48", // DONE
  Tm49 = "tm49", // DONE
  Tm50 = "tm50", // DONE
  Tm51 = "tm51", // DONE
  Tm52 = "tm52", // DONE
  Tm53 = "tm53", // DONE
  Tm54 = "tm54", // DONE
  Tm55 = "tm55", // DONE
}
